version: '3'

services:
  rabbit_mq:
    build:
      context: rabbitmq
    container_name: rabbit_mq
    ports:
      - "5672:5672" #amqp
      - "15672:15672" #http
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  postgres_notifications:
    container_name: postgres_notifications
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  user_api:
    container_name: user_api
    build:
      context: notifications_api
      dockerfile: Dockerfile_user
    depends_on:
      - rabbit_mq
      - postgres

  admin_api:
    container_name: admin_api
    build:
      context: notifications_api
      dockerfile: Dockerfile_admin
    depends_on:
      - rabbit_mq

  consumer:
    container_name: consumer
    build:
      context: notifications_api/worker
    depends_on:
      - rabbit_mq
